### ISSUE TITLE
Scary

### ISSUE THREAD

**Issue by Kathund** [madelynwith5ns/StarsignJS#1]
This project scares me

**Comment by madelynwith5ns** [comment]
thats intentional
also skill issue
have you tried using tailwind + the bazzinated fooific barinator?

**Comment by Kathund** [comment]
Your missing tailwind in this project

**Comment by madelynwith5ns** [comment]
Tailwind is made obsolete by XSS (the bash-based CSS generator).

**Comment by Kathund** [comment]
I thought we needed more "useful" stuff here added

**Comment by madelynwith5ns** [comment]
The points brought up in this issue have been made invalid by the addition of WebFuck for the frontend.
